# -*- coding: utf-8 -*-
"""MiniProjeto_02ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19F1zRScp46qFyrhpmcGiznjF5S7KgTyv

# **Integrantes do projeto:**
*   João Pedro Gomes Marchi - 11202522190
*   Carlos Alberto Brocco   - 11202522215

# Mini Projeto - Orientações

▶ **Atividade INDIVIDUAL ou em PARES**

Submissões com mais de dois membros no grupo ficam sem nota.

▶ **Objetivo**

Neste mini-projeto, você irá analisar indicadores sociais ou econômicos utilizando programação, estatística e visualização gráfica. O projeto envolve trabalhar com dados temporais (dados que cobrem vários anos) e aplicar técnicas simples de análise de dados.


Você irá escolher dois indicadores de um país à sua escolha. A fonte de dados tem informações por ano, por isso você precisará escolher:

  * *Período ANO*: Escolha um ano específico (por exemplo, 2020) e

  * *Período FAIXA*: Escolha uma faixa de anos para comparar (por exemplo, de 2015 a 2025).


O objetivo do projeto é analisar esses dois indicadores, considerando os dois períodos, e gerar visualizações gráficas, além de aplicar uma regressão simples.

Passos a seguir para a análise:

  * Definição das Hipóteses: Qualquer trabalho de análise passa por definir as hipóteses sobre os dados a serem manipulados. Assim, após feito a escolha do país, indicadores e os dados, define DUAS hipóteses da sua análise.

  * Ler os dados: O primeiro passo é importar os dados dos indicadores escolhidos (em formato CSV).

  * Estatística descritiva: Calcular algumas estatísticas básicas para os indicadores, como a média, mediana, desvio padrão e outros valores descritivos para o período FAIXA.

  * Criar os gráficos:

     * Evolução temporal (gráfico de linha): Mostre como o indicador evoluiu ao longo do tempo no período FAIXA escolhido. A linha do gráfico pode mostrar, por exemplo, como a taxa de desemprego de um país muda ao longo de vários anos.

  * Regressão simples: Aplique uma regressão simples entre os dois indicadores no período ANO e FAIXA. A regressão ajuda a entender a relação entre esses dois indicadores ao longo do tempo.

  * Conclusão: Discuta os resultados de suas análises (principalmente a regressão) frente às suas hipóteses. Eles confirmar ou refutam suas hipóteses originais? Ainda, faça uma reflexação crítica das limitações do seu estudo.

▶ **Fonte dos Dados**

Os dados podem ser obtidos no site Gapminder (https://www.gapminder.org/data/), que fornece uma ampla gama de indicadores sociais e econômicos. Esses dados estão disponíveis em arquivos CSV ou XLS.

▶ **Formato de Entrega**

Você deverá entregar a solução em um notebook do Google Colab (formato .ipynb). Certifique-se de anexar o arquivo de dados CSV utilizado no seu projeto. O seu código será executado diretamente no ambiente do Colab.

▶ **Critério de Avaliação**

| **Critério**                                | **Descrição**                                                                                             | **Pontuação Máxima**    |
| ------------------------------------------- | --------------------------------------------------------------------------------------------------------- | ----------------------- |
| **1. Hipóteses**  | Hipótese com suposição razoável, comparável entre duas vriáveis ou categorias e refutável (que pode ser negada pelos dados).                                       | 0,5 ponto                 |
| **2. Funcionalidade de Leitura dos Dados**  | Leitura correta do arquivo CSV e visualização das primeiras linhas.                                       | 0,5 ponto                 |
| **3. Estatísticas Descritivas**             | Aplicação correta da estatística descritiva para os períodos ANO e FAIXA (média, mediana, desvio padrão). | 1,5 pontos              |
| **4. Gráfico de Evolução Temporal (linha)** | Gráfico de linha mostrando a evolução do indicador no período FAIXA.                                      | 1,5 pontos              |
| **5. Implementação de Regressão Simples**   | Aplicação de regressão simples entre os dois indicadores, com interpretação dos resultados para o período ANO.               | 2,5 pontos                |
| **6. Conclusão**   | Discussão dos resultados frente às hipóteses estabelecidas, bem como reflexão das limitações.         | 2,5 pontos                |

### **Pontuação Final**

* A pontuação mínima é **0 pontos** (se não rodar ou houver erros críticos).
* A pontuação será descontada por funcionalidades não entregues ou erradas.
* TODOS os trabalhos serão comparados entre sim (automaticamente). Caso haja a identificação de soluções idênticas ou muito parecidas (*threshold* > 90%), todos os trabalhos ficam sem nota.

# **Mini projeto #2**

## **Canadá**

### **Período ANO: 2020 Período FAIXA: 2010 a 2020**
### **Hipóteses**
Hipótese 1 (H1): A taxa de fertilidade total no Canadá apresentou uma tendência de declínio entre 2010 e 2020.

Hipótese 2 (H2): Existe uma correlação negativa entre o ano e a taxa de fertilidade total no Canadá, indicando que, ao longo do tempo, a taxa de natalidade tende a diminuir.
"""

# -----------------------------
# Importações
# -----------------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
import seaborn as sns
import numpy as np

print("--- Tudo certo!!! ---")
print("--- Começando a criar os dados e gráficos ---")

url = "https://drive.google.com/uc?id=1_I3qRtvPrd--QYsFiOuImKRPFTWJEr33"

df_fertility = pd.read_csv(url, sep=",")  # ajuste sep se necessário
print("Dados de fertilidade carregados com sucesso!")
print(df_fertility.head())  # para conferir



"""### **Faixa de 10 anos (2010 - 2020)**"""

# Filtrar apenas os dados do Canadá
canada = df_fertility[df_fertility['country'] == 'Canada'].iloc[0]

# Definir os anos do período (2010 a 2020)
anos_10 = [str(ano) for ano in range(2010, 2021)]

# Pegar apenas os valores desses anos
fertilidade_canada_10anos = canada[anos_10].dropna().astype(float)

# Calcular estatísticas
media = fertilidade_canada_10anos.mean()
mediana = fertilidade_canada_10anos.median()
desvio_padrao = fertilidade_canada_10anos.std()
minimo = fertilidade_canada_10anos.min()
maximo = fertilidade_canada_10anos.max()

# -----------------------------
# Estatísticas
# -----------------------------
print("Estatísticas da Taxa de Fertilidade no Canadá (2010-2020):")
print("----------------------------------------------------------")
print("Média:", round(media, 2))
print("Mediana:", round(mediana, 2))
print("Desvio Padrão:", round(desvio_padrao, 2))
print("Mínimo:", round(minimo, 2))
print("Máximo:", round(maximo, 2))

# -----------------------------
# Gráfico 01
# -----------------------------
plt.figure(figsize=(10, 6))  # tamanho da figura
sns.lineplot(
    x=fertilidade_canada_10anos.index,  # anos
    y=fertilidade_canada_10anos.values, # valores da taxa
    marker='o'                   # marcar os pontos
)

plt.title("Evolução da Taxa de Fertilidade no Canadá (2010-2020)")
plt.xlabel("Ano")
plt.ylabel("Crianças por Mulher")

plt.grid(True)          # grade no fundo
plt.xticks(rotation=45) # rotacionar os anos
plt.tight_layout()      # ajustar espaçamento

plt.show()

anos_10 = np.array([int(ano) for ano in fertilidade_canada_10anos.index]).reshape(-1, 1)

# Pega os valores da taxa de fertilidade
taxas = fertilidade_canada_10anos.values

modelo = LinearRegression()
modelo.fit(anos_10, taxas)

# Fazer previsões
previsoes = modelo.predict(anos_10)

# -----------------------------
# Coeficientes da regressão
# -----------------------------
inclinação = modelo.coef_[0]  # coeficiente angular
intercepto = modelo.intercept_  # ponto onde a linha cruza o eixo Y

print("\n--- Resultados da Regressão Linear (Canadá) ---")
print(f"Inclinação: {inclinação:.4f}")
print(f"Intercepto: {intercepto:.2f}")
print(f"Equação: Fertilidade = {inclinação:.4f} * Ano + {intercepto:.2f}\n")

# -----------------------------
# Gráfico
# -----------------------------
plt.figure(figsize=(10, 6))
sns.scatterplot(x=anos_10.flatten(), y=taxas, label="Dados reais")

# Linha de regressão
sns.lineplot(x=anos_10.flatten(), y=previsoes, color="red", label="Linha de Regressão")

plt.title("Regressão Linear - Taxa de Fertilidade no Canadá (2010-2020)")
plt.xlabel("Ano")
plt.ylabel("Crianças por Mulher")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# -----------------------------
# Valor de 2020
# -----------------------------
valor_2020 = fertilidade_canada_10anos["2020"]
print(f"\nTaxa de Fertilidade no Canadá em 2020: {valor_2020}")

anos_grafico = [1800, 2025, 2100]
fertilidade = [5.72, 1.49, 1.5]

# Criar o gráfico de barras
plt.figure(figsize=(10, 6))
barras = plt.bar(anos_grafico, fertilidade, color=['wheat', 'silver', 'gray'])

# Colocar o valor no topo de cada barra
for barra in barras:
    altura = barra.get_height()
    plt.text(
        barra.get_x() + barra.get_width() / 2,
        altura + 0.1,
        f'{altura:.2f}',
        ha='center'
    )

# Adicionar título e rótulos
plt.title('Fertilidade Total no Canadá: Comparação entre Anos Selecionados')
plt.xlabel('Ano')
plt.ylabel('Crianças por Mulher')

# Ajustar limite do eixo y para melhor visualização
plt.ylim(0, 6)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# -----------------------------
# Gráfico
# -----------------------------
plt.show()

"""### **Faixa de 300 anos (1800-2100)**"""

# Filtrar apenas os dados do Canadá
canada = df_fertility[df_fertility['country'] == 'Canada'].iloc[0]

# Definir os anos do período (1800 a 2100)
anos_300 = [str(ano) for ano in range(1800, 2100)]

# Pegar apenas os valores desses anos
fertilidade_canada_300anos = canada[anos_300].dropna().astype(float)

# Calcular estatísticas
media = fertilidade_canada_300anos.mean()
mediana = fertilidade_canada_300anos.median()
desvio_padrao = fertilidade_canada_300anos.std()
minimo = fertilidade_canada_300anos.min()
maximo = fertilidade_canada_300anos.max()

# -----------------------------
# Estatísticas
# -----------------------------
print("Estatísticas da Taxa de Fertilidade no Canadá (1800-2100):")
print("----------------------------------------------------------")
print("Média:", round(media, 2))
print("Mediana:", round(mediana, 2))
print("Desvio Padrão:", round(desvio_padrao, 2))
print("Mínimo:", round(minimo, 2))
print("Máximo:", round(maximo, 2))

# -----------------------------
# Gráfico 02
# -----------------------------
plt.figure(figsize=(15, 6))

sns.lineplot(
    x=fertilidade_canada_300anos.index,
    y=fertilidade_canada_300anos.values,
    label="Taxa de Fertilidade 1800-2100"
)

plt.title("Evolução da Taxa de Fertilidade no Canadá (1800-2100)")
plt.xlabel("Ano")
plt.ylabel("Crianças por Mulher")
plt.legend(loc='best')

# Define ticks para anos representativos
anos_para_mostrar = [1800, 1900, 2000, 2100]

plt.xticks(anos_para_mostrar, rotation=45)

plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

plt.show()

anos_reg_300 = np.array([int(ano) for ano in fertilidade_canada_300anos.index]).reshape(-1, 1)

# Pega os valores da taxa de fertilidade
taxas = fertilidade_canada_300anos.values

modelo = LinearRegression()
modelo.fit(anos_reg_300, taxas)

# Fazer previsões
previsoes = modelo.predict(anos_reg_300)

# -----------------------------
# Coeficientes da regressão
# -----------------------------
inclinação = modelo.coef_[0]  # coeficiente angular
intercepto = modelo.intercept_  # ponto onde a linha cruza o eixo Y

print("\n--- Resultados da Regressão Linear (Canadá) ---")
print(f"Inclinação: {inclinação:.4f}")
print(f"Intercepto: {intercepto:.2f}")
print(f"Equação: Fertilidade = {inclinação:.4f} * Ano + {intercepto:.2f}\n")

# -----------------------------
# Gráfico
# -----------------------------
plt.figure(figsize=(10, 6))
sns.scatterplot(x=anos_reg_300.flatten(), y=taxas, label="Dados reais")

# Linha de regressão
sns.lineplot(x=anos_reg_300.flatten(), y=previsoes, color="red", label="Linha de Regressão")

plt.title("Regressão Linear - Taxa de Fertilidade no Canadá (1800-2100)")
plt.xlabel("Ano")
plt.ylabel("Crianças por Mulher")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""### **Diferenças entre os anos 1800, 1900 e 2000, período de 100 anos em cada um**
Primeiro período 1800 - 1899
Segundo período 1900 - 1999
Segundo período 2000 - 2100

"""

# Definir os anos do período
anos = [str(ano) for ano in range(1800, 1899)]
anos2 = [str(ano) for ano in range(1900, 1999)]
anos3 = [str(ano) for ano in range(2000, 2100)]

# Pegar apenas os valores desses anos
fertilidade_canada = canada[anos].dropna().astype(float)
fertilidade_canada2 = canada[anos2].dropna().astype(float)
fertilidade_canada3 = canada[anos3].dropna().astype(float)

# Calcular estatísticas 1 (1800-1899)
media1 = fertilidade_canada.mean()
mediana1 = fertilidade_canada.median()
desvio_padrao1 = fertilidade_canada.std()
minimo1 = fertilidade_canada.min()
maximo1 = fertilidade_canada.max()

# Calcular estatísticas 2 (1900-1999)
media2 = fertilidade_canada2.mean()
mediana2 = fertilidade_canada2.median()
desvio_padrao2 = fertilidade_canada2.std()
minimo2 = fertilidade_canada2.min()
maximo2 = fertilidade_canada2.max()

# Calcular estatísticas 3 (2000-2100)
media3 = fertilidade_canada3.mean()
mediana3 = fertilidade_canada3.median()
desvio_padrao3 = fertilidade_canada3.std()
minimo3 = fertilidade_canada3.min()
maximo3 = fertilidade_canada3.max()

# -----------------------------
# Estatísticas 1 (1800-1899)
# -----------------------------
print("Estatísticas da Taxa de Fertilidade no Canadá (1800-1899):")
print("----------------------------------------------------------")
print("Média:", round(media1, 2))
print("Mediana:", round(mediana1, 2))
print("Desvio Padrão:", round(desvio_padrao1, 2))
print("Mínimo:", round(minimo1, 2))
print("Máximo:", round(maximo1, 2),"\n")

# -----------------------------
# Estatísticas 2 (1900-1999)
# -----------------------------
print("Estatísticas da Taxa de Fertilidade no Canadá (1900-1999):")
print("----------------------------------------------------------")
print("Média:", round(media2, 2))
print("Mediana:", round(mediana2, 2))
print("Desvio Padrão:", round(desvio_padrao2, 2))
print("Mínimo:", round(minimo2, 2))
print("Máximo:", round(maximo2, 2),"\n")

# -----------------------------
# Estatísticas 3 (2000-2100)
# -----------------------------
print("Estatísticas da Taxa de Fertilidade no Canadá (2000-2100):")
print("----------------------------------------------------------")
print("Média:", round(media3, 2))
print("Mediana:", round(mediana3, 2))
print("Desvio Padrão:", round(desvio_padrao3, 2))
print("Mínimo:", round(minimo3, 2))
print("Máximo:", round(maximo3, 2),"\n")

# -----------------------------
# Gráfico 03 - Comparação dos três períodos
# -----------------------------
plt.figure(figsize=(15, 6))

# Converter índices para valores numéricos para plotagem
anos_1800 = [int(ano) for ano in fertilidade_canada.index]
anos_1900 = [int(ano) for ano in fertilidade_canada2.index]
anos_2000 = [int(ano) for ano in fertilidade_canada3.index]

# Plotar cada período com uma cor diferente e rótulo
plt.plot(anos_1800, fertilidade_canada.values, label="1800-1899")
plt.plot(anos_1900, fertilidade_canada2.values, label="1900-1999")
plt.plot(anos_2000, fertilidade_canada3.values, label="2000-2100")

plt.title("Comparação da Taxa de Fertilidade no Canadá por Períodos de 100 Anos")
plt.xlabel("Ano")
plt.ylabel("Crianças por Mulher")
plt.legend(loc='best')

# Define ticks para anos representativos
anos_para_mostrar = [1800, 1900, 2000, 2100]

plt.xticks(anos_para_mostrar, rotation=45)

plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

plt.show()

"""## **Conclusões da pesquisa**

Apontamentos:
- Bom primeiramente, eu não escolhi o Canadá por algum motivo muito especifico mas sim só porque eu gosto do país e por isso escolhi.

Análises:
- Vendo pelos resultados apresentados, é possível notar uma diminuição na natalidade em 10 anos ou até mesmo em 200 anos se pegarmos de base o primeiro ano do csv e compararmos ao presente, isso pode acontecer por diversos motivos mas, penso eu que o maior motivo da taxa de natalidade ter diminuido tenha sido o aumento do custo de vida com o decorrer dos anos, é possível até notar alguma váriação no gráfico, alguns anos a taxa pode aumentar mas no geral a taxa tende a diminuir e descer;
- Comparando com 1800 a 2025 podemos ver uma diferença enorme na taxa, uma difirença de 4.23;
"""